language: android

android:
  components:
    - build-tools-20.0.0
    - android-20
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

script:
  ./gradlew assembleDebug
